# Disable the Gradle daemon for Continuous Integration servers as correctness 
# is usually a priority over speed in CI environments. Using a fresh 
# runtime for each build is more reliable since the runtime is completely 
# isolated from any previous builds. 
#variables: 
#    GRADLE_OPTS: "-Dorg.gradle.daemon=false"
#
#stages: 
#    - build 
#    - test
#
#build: 
#    stage: build 
#    script: -./gradlew assemble 
#test: 
#    stage: test 
#    script: 
#        - ./gradlew test
image: java:8-jdk

stages:
  - build
  - test

before_script:
#  - echo `pwd` # debug
#  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug
  variables:
  GRADLE_USER_HOME: '.gradle-cache'

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week
  only:
    - master

test:
  stage: test
  script:
    - ./gradlew check


after_script:
  - echo "End CI"