INSERT INTO country (country_name, country_code) VALUES
                                                         ('Austria', 'AT'),
                                                         ('Belgium', 'BE'),
                                                         ('Bulgaria', 'BG'),
                                                         ('Croatia', 'HR'),
                                                         ('Cyprus', 'CY'),
                                                         ('Czech Republic', 'CZ'),
                                                         ('Denmark', 'DK'),
                                                         ('Estonia', 'EE'),
                                                         ('Finland', 'FI'),
                                                         ('France', 'FR'),
                                                         ('Germany', 'DE'),
                                                         ('Greece', 'GR'),
                                                         ('Hungary', 'HU'),
                                                         ('Iceland', 'IS'),
                                                         ('Ireland', 'IE'),
                                                         ('Italy', 'IT'),
                                                         ('Latvia', 'LV'),
                                                         ('Lithuania', 'LT'),
                                                         ('Luxembourg', 'LU'),
                                                         ('Malta', 'MT'),
                                                         ('Netherlands', 'NL'),
                                                         ('Norway', 'NO'),
                                                         ('Poland', 'PL'),
                                                         ('Portugal', 'PT'),
                                                         ('Romania', 'RO'),
                                                         ('Slovakia', 'SK'),
                                                         ('Slovenia', 'SI'),
                                                         ('Spain', 'ES'),
                                                         ('Sweden', 'SE'),
                                                         ('Switzerland', 'CH'),
                                                         ('United Kingdom', 'GB')
;

INSERT INTO city (city_name, country_id) VALUES
                                             ('Vienna', 1),
                                             ('Brussels', 2),
                                             ('Sofia', 3),
                                             ('Zagreb', 4),
                                             ('Nicosia', 5),
                                             ('Prague', 6),
                                             ('Copenhagen', 7),
                                             ('Tallinn', 8),
                                             ('Helsinki', 9),
                                             ('Paris', 10),
                                             ('Berlin', 11),
                                             ('Athens', 12),
                                             ('Budapest', 13),
                                             ('Reykjavik', 14),
                                             ('Dublin', 15),
                                             ('Rome', 16),
                                             ('Riga', 17),
                                             ('Vilnius', 18),
                                             ('Luxembourg', 19),
                                             ('Valletta', 20),
                                             ('Amsterdam', 21),
                                             ('Oslo', 22),
                                             ('Warsaw', 23),
                                             ('Lisbon', 24),
                                             ('Bucharest', 25),
                                             ('Bratislava', 26),
                                             ('Ljubljana', 27),
                                             ('Madrid', 28),
                                             ('Stockholm', 29),
                                             ('Bern', 30),
                                             ('London', 31)
;
